gimmecash/config/routes.rb
Gimmecash::Application.routes.draw do

  resources :projects
  resources :users

  resources :sessions, :only => [:new, :create, :destroy]
  root :to => 'projects#index'

end

gimmecash/app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
end

gimmecash/app/models/user.rb
class User < ActiveRecord::Base
	has_many :projects
end

gimmecash/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

gimmecash/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects= Project.all
	end

	def show
		@project = Project.find(params[:id])
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(projects_params)
		@project.user_id = 1.to_i
		if @project.save
			redirect_to projects_path
		else
			render :new
		end
		end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])

		if @project.update_attributes(projects_params)
			redirect_to projects_path
		else
			render :edit
		end
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to projects_path
	end

	private
	def projects_params
		params.require(:project).permit(:title,:description,:start_date, :end_date, :goal, :active)
	end


end

gimmecash/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

gimmecash/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to projects_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

gimmecash/app/helpers/application_helper.rb
module ApplicationHelper
end

gimmecash/app/helpers/projects_helper.rb
module ProjectsHelper
end

gimmecash/app/helpers/sessions_helper.rb
module SessionsHelper
end

gimmecash/app/helpers/users_helper.rb
module UsersHelper
end

gimmecash/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gimmecash</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

gimmecash/app/views/projects/_form.html.erb
<%= form_for @project, html: {class: "project_form"} do |f| %>
    <div>
    	<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div>
		<%= f.label :description %>
		<%= f.text_field :description %>
	</div>
	<div>
		<%= f.label :start_date %>
		<%= f.date_field(:start_date) %>
	</div>
	<div>
		<%= f.label :end_date %>
		<%= f.date_field(:end_date) %>
	</div>
	<div>
		<%= f.label :goal %>
		<%= f.number_field :goal %>
	</div>
	<div>
		<%= f.label :active %>
		<%= f.check_box :active %>
	</div>
	<div>
		<%= f.submit %>
	</div>
<% end %>

gimmecash/app/views/projects/edit.html.erb
<%= render :partial => 'form' %>

gimmecash/app/views/projects/index.html.erb
<% @projects.each do |project| %>

<ul>

	<li> <%= link_to project.title, project_path(project.id) %> </li>
	<li> Description: <%= project.description %> </li>
	<li> Goal: <%= number_to_currency(project.goal, precision: 2) %> </li>
	<li> Start Date: <%= project.start_date %> </li>
	<li> End Date: <%= project.end_date %> </li>
	<li> Status: <%= project.active %> </li>
</ul>

<% end %>

gimmecash/app/views/projects/new.html.erb
	<%= render :partial => 'form' %>

gimmecash/app/views/projects/show.html.erb
<%= link_to "Back to Projects", projects_path %>

<h1>TITLE: <%=  @project.title %> </h1>
<p>
DESCRIPTION: <%=  @project.description %><br>
GOAL: <%= number_to_currency(@project.goal, precision: 2) %><br>
START DATE: <%=  @project.start_date %><br>
END DATE: <%=  @project.end_date %><br>
</p>

<p>
<%= link_to "Edit", edit_project_path(@project) %>
<%= link_to "Delete", @project, :confirm => "Are you sure?", :method => :delete %>
</p>

gimmecash/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

gimmecash/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>